language: php

before_script:
  - composer self-update
  - composer update --prefer-source

script: phpunit --testsuite travis-ci --coverage-clover tests/clover.xml

after_script:
 - php vendor/bin/coveralls

php:
  - 5.4
  - 5.5
